#!/bin/bash
wpout=/tmp/check_wordpress_$1.log
 
if [ $# -eq 0 ]; then
    echo Llamada: $0 [www.meine-domain.de]
    exit
      else
    # /PFAD/ZUM/check_wordpress.php ANPASSEN !
    curl -s $1/PFAD/ZUM/check_wordpress.php > $wpout
fi
 
# Check for OK
if grep -q "OK" $wpout; then
    grep OK $wpout
    exit 0
fi
 
# Check for WARNING
if grep -q "WARNING" $wpout; then
    egrep '(WARNING|Plugins)' $wpout
    exit 1
fi